name: JMeter Master

on:
  workflow_dispatch:
    inputs:
      slave_ip:
        description: 'IP address of the JMeter slave'
        required: true
        type: string

jobs:
  jmeter-master:
    runs-on: ubuntu-latest
    services:
      jmeter-slave:
        image: justb4/jmeter
        ports:
          - 1099/tcp
          - 60000/tcp
        options: --name jmeter-slave
        env:
          JVM_ARGS: -Dserver.rmi.ssl.disable=true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create user.properties file
      run: echo "server.rmi.ssl.disable=true" > $GITHUB_WORKSPACE/user.properties

    - name: Verify user.properties content
      run: cat $GITHUB_WORKSPACE/user.properties

    - name: Test connectivity to JMeter slave
      run: |
        sudo apt-get update
        sudo apt-get install -y iputils-ping netcat
        echo "Pinging JMeter slave..."
        ping -c 4 ${{ github.event.inputs.slave_ip }}
        echo "Testing port 1099..."
        nc -zv ${{ github.event.inputs.slave_ip }} 1099
        echo "Testing port 60000..."
        nc -zv ${{ github.event.inputs.slave_ip }} 60000

    - name: Configure and run JMeter test
      run: |
        echo "${{ github.event.inputs.slave_ip }}" > $GITHUB_WORKSPACE/slaves.txt
        docker run \
          --network="host" \
          -v $GITHUB_WORKSPACE:/workspace \
          justb4/jmeter \
          -n -t /workspace/your_test_plan.jmx \
          -R${{ github.event.inputs.slave_ip }} \
          -Dserver.rmi.ssl.disable=true \
          -Duser.properties=/workspace/user.properties

    - name: Upload JTL file
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: $GITHUB_WORKSPACE/*.jtl

    - name: Post-test cleanup
      run: echo "Test completed. Cleaning up..."
