name: JMeter Master

on:
  workflow_dispatch:
    inputs:
      slave_ip:
        description: 'IP address of the JMeter slave'
        required: true
        type: string

jobs:
  jmeter-master:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker (optional)
      # Only necessary if not already installed on the runner
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
        # ... (rest of installation steps)

    - name: Generate (if not exists) and copy rmi_keystore.jks
      run: |
        if [ ! -f $GITHUB_WORKSPACE/jmeter/bin/rmi_keystore.jks ]; then
          sh $GITHUB_WORKSPACE/jmeter/bin/create-rmi-keystore
        fi
        scp $GITHUB_WORKSPACE/jmeter/bin/rmi_keystore.jks user@${{ github.event.inputs.slave_ip }}:/path/to/jmeter/bin (or equivalent)

    - name: Create custom user.properties
      run: |
        echo "server.rmi.ssl.disable=true" >> $GITHUB_WORKSPACE/user.properties

    - name: Debug Network (optional)
      run: |
        echo "Pinging from runner to ${{ github.event.inputs.slave_ip }}"
        ping -c 4 ${{ github.event.inputs.slave_ip }}

    - name: Run JMeter Master
      run: |
        echo "${{ github.event.inputs.slave_ip }}" > $GITHUB_WORKSPACE/slaves.txt
        sudo docker run \
          --network host \
          -v $GITHUB_WORKSPACE:/workspace \
          -v $GITHUB_WORKSPACE/user.properties:/opt/apache-jmeter-5.4.1/bin/user.properties \
          -v $GITHUB_WORKSPACE/jmeter/bin/rmi_keystore.jks:/opt/apache-jmeter-5.4.1/bin/rmi_keystore.jks \
          justb4/jmeter:latest \
          -n -t /workspace/Demo.jmx -Duser.properties=/opt/apache-jmeter-5.4.1/bin/user.properties -R${{ github.event.inputs.slave_ip }}

    - name: Upload JTL file
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: $GITHUB_WORKSPACE/*.jtl

    - name: Post-test cleanup
      run: |
        echo "Test completed. Cleaning up..."
