name: JMeter Master

on:
  workflow_dispatch:

jobs:
  jmeter-master:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xvzf apache-jmeter-5.4.1.tgz
        export JMETER_HOME=$PWD/apache-jmeter-5.4.1
        export PATH=$JMETER_HOME/bin:$PATH

    - name: Configure and run JMeter test
      run: |
        echo "Fetching slave IP address..."
        SLAVE_IP=$(aws ec2 describe-instances --instance-ids <INSTANCE_ID> --query 'Reservations[0].Instances[0].PrivateIpAddress' --output text)
        echo "slave_ip=$SLAVE_IP" >> $GITHUB_ENV
        echo "Slave IP: $SLAVE_IP"

        echo "Setting up JMeter properties..."
        echo "remote_hosts=$SLAVE_IP" > $JMETER_HOME/bin/user.properties

        echo "Running JMeter test..."
        jmeter -n -t your_test_plan.jmx -R $SLAVE_IP

    - name: Post-test cleanup
      run: |
        echo "Test completed. Cleaning up..."
