name: JMeter Master

on:
  workflow_dispatch:
    inputs:
      slave_ip:
        description: 'IP address of the JMeter slave'
        required: true
        type: string

jobs:
  jmeter-master:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create user.properties file
      run: echo "server.rmi.ssl.disable=true" > $GITHUB_WORKSPACE/user.properties

    - name: Verify user.properties content
      run: cat $GITHUB_WORKSPACE/user.properties

    - name: Configure and run JMeter test
      run: |
        echo "${{ github.event.inputs.slave_ip }}" > $GITHUB_WORKSPACE/slaves.txt
        docker run \
          --network="host" \
          -v $GITHUB_WORKSPACE:/workspace \
          justb4/jmeter \
          -n -t /workspace/Demo.jmx \
          -R${{ github.event.inputs.slave_ip }} \
          -Dserver.rmi.ssl.disable=true \
          -Duser.properties=/workspace/user.properties

    - name: Upload JTL file
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: $GITHUB_WORKSPACE/*.jtl

    - name: Post-test cleanup
      run: echo "Test completed. Cleaning up..."
