name: JMeter Master

on:
  workflow_dispatch:

jobs:
  jmeter-master:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xvzf apache-jmeter-5.4.1.tgz
        export JMETER_HOME=$PWD/apache-jmeter-5.4.1
        export PATH=$JMETER_HOME/bin:$PATH

    - name: Configure and run JMeter test
      run: |
        echo "slave_ip=$(aws ec2 describe-instances --instance-ids <INSTANCE_ID> --query 'Reservations[0].Instances[0].PrivateIpAddress' --output text)" >> $GITHUB_ENV
        jmeter -n -t your_test_plan.jmx -R ${{ env.slave_ip }}

    - name: Post-test cleanup
      run: |
        echo "Test completed. Cleaning up..."
