name: JMeter Master

on:
  workflow_dispatch:
    inputs:
      slave_ip:
        description: 'IP address of the JMeter slave'
        required: true
        type: string

jobs:
  jmeter-master:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo yum update -y
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Debug Network from runner
      run: |
        echo "Pinging from runner to ${{ github.event.inputs.slave_ip }}"
        ping -c 4 ${{ github.event.inputs.slave_ip }}

    - name: Debug Network from Docker container
      run: |
        echo "Pinging from Docker container to ${{ github.event.inputs.slave_ip }}"
        sudo docker run --network host alpine ping -c 4 ${{ github.event.inputs.slave_ip }}

    - name: Run JMeter Master
      run: |
        echo "${{ github.event.inputs.slave_ip }}" > $GITHUB_WORKSPACE/slaves.txt
        sudo docker run \
          --network host \
          -v $GITHUB_WORKSPACE:/workspace \
          justb4/jmeter:latest \
          -n -t /workspace/Demo.jmx -R${{ github.event.inputs.slave_ip }}

    - name: Upload JTL file
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: $GITHUB_WORKSPACE/*.jtl

    - name: Post-test cleanup
      run: |
        echo "Test completed. Cleaning up..."
